#! /bin/sh

### BEGIN INIT INFO
# Provides:          Fan for MyDV-nano
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:    
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Provide automated cooling
# Description: Provide cooling based on cpu-temperature
### END INIT INFO

N=/etc/init.d/CastFan

set -e

case "$1" in
  start)
	/usr/bin/cast-fan
	echo "Starting Fan-service" >&2
	exit 0
	;;
  stop)
	killall cast-fan
	exit 0
	;;
  reload|restart|force-reload|status)
	;;
  *)
	echo "Usage: $N {start|stop}" >&2
	exit 1
	;;
esac

exit 0
